apiVersion: extensions/v1beta1
kind: DaemonSet
metadata:
  name: container-linux-torcx-pre-hook
  namespace: kube-system
spec:
  template:
    metadata:
      labels:
        app: container-linux-torcx-pre-hook
    spec:
      nodeSelector:
        container-linux-update.v1.coreos.com/before-reboot: "true"
      tolerations:
      - key: node-role.kubernetes.io/master
        operator: Exists
        effect: NoSchedule
      containers:
      - name: update-agent
        image: quay.io/coreos/tectonic-torcx-amd64:latest
        command:
        - "/tectonic-torcx-hook-pre"
        - "--verbose=debug"
          #- "--node-annotation=container-linux-update.v1.coreos.com/tectonic-torcx-pre-hook-ok"
          # Add this annotation to the container-linux-update-operator configuration
          # see: https://github.com/coreos/container-linux-update-operator/blob/master/doc/before-after-reboot-checks.md
        - "--sleep=604800" # sleep for a week after success; the operator will deschedule us
        volumeMounts:
          - mountPath: /usr/share
            name: usr-share
            readOnly: true
          - mountPath: /var/lib/torcx
            name: var-lib-torcx
          - mountPath: /etc/torcx
            name: etc-torcx
          - mountPath: /run/metadata
            name: run-metadata
            readOnly: true
          - mountPath: /run/systemd
            name: run-systemd
          - mountPath: /run/torcx
            name: run-torcx
            readOnly: true
          - mountPath: /etc/kubernetes
            name: etc-kubernetes
          - mountPath: /var/run/dbus
            name: var-run-dbus
          - mountPath: /usr/lib/os-release
            name: usr-lib-os-release
            readOnly: true
          - mountPath: /etc/coreos
            name: etc-coreos
            readOnly: true
          - mountPath: /etc/ssl/certs/ca-certificates.crt
            name: ca-certificates
            readOnly: true
          - mountPath: /tmp
            name: tmp
          - mountPath: /dev/log
            name: dev-log
        env:
        - name: NODE
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
      volumes:
      - name: usr-share
        hostPath:
          path: /usr/share
      - name: var-lib-torcx
        hostPath:
          path: /var/lib/torcx
      - name: etc-torcx
        hostPath:
          path: /etc/torcx
      - name: run-metadata
        hostPath:
          path: /run/metadata
      - name: run-systemd
        hostPath:
          path: /run/systemd
      - name: run-torcx
        hostPath:
          path: /run/torcx
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: var-run-dbus
        hostPath:
          path: /var/run/dbus
      - name: usr-lib-os-release
        hostPath:
          path: /usr/lib/os-release
      - name: etc-coreos
        hostPath:
          path: /etc/coreos
      - name: ca-certificates
        hostPath:
          path: /usr/share/ca-certificates/ca-certificates.crt
      - name: tmp
        emptyDir: {}
      - name: dev-log
        hostPath:
            path: /dev/log
